-- 检查和修复数据库表结构
USE blogdb;

-- 检查当前表结构
SHOW CREATE TABLE posts;
SHOW CREATE TABLE categories;
SHOW CREATE TABLE tags;
SHOW CREATE TABLE post_tags;

-- 查看所有列信息
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    IS_NULLABLE, 
    CHARACTER_MAXIMUM_LENGTH,
    COLUMN_KEY,
    EXTRA
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'blogdb' 
AND TABLE_NAME = 'posts';

-- 如果发现问题，使用以下语句修复

-- 1. 确保posts表有所有必要的列
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS id BIGINT AUTO_INCREMENT PRIMARY KEY;
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL;
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS `desc` VARCHAR(500);
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS content TEXT NOT NULL;
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS author VARCHAR(255);
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS created_at DATETIME;
-- ALTER TABLE posts ADD COLUMN IF NOT EXISTS category_id BIGINT;

-- 2. 如果content字段类型不是TEXT，修改为TEXT
-- ALTER TABLE posts MODIFY COLUMN content TEXT NOT NULL;

-- 3. 确保content字段长度足够（如果当前是VARCHAR且长度不够）
-- ALTER TABLE posts MODIFY COLUMN content LONGTEXT NOT NULL;

-- 4. 检查外键约束
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'blogdb'
AND TABLE_NAME = 'posts';

-- 5. 显示所有索引
SHOW INDEX FROM posts;
